apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-store-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-store
  template:
    metadata:
      labels:
        app: image-store
    spec:
      containers:
        - name: image-store
          image: image-store-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENV_VARIABLE_1
              value: value1
            - name: ENV_VARIABLE_2
              value: value2