
Certainly! Here's an example service file for your image store application:

yaml
Copy code
# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: image-store-service
spec:
  selector:
    app: image-store
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080